### ISSUE TITLE
Explicit dependencies

### ISSUE THREAD

**Issue by pradal** [VirtualPlants/draco_stem#1]
Define for each packages the dependencies:
- **cellcomplex**:
  - numpy, scipy, openalea.container, [vtk, openalea.plantgl]
- **mesh**
  - openalea.core, tissuelab, oalab
    -draco_stem
  - openalea.image, tissue_analysis, openalea.container

**Comment by gcerutti** [comment]
Dependencies made explicit in the main ReadMe (along with package restructuration) ;)
